name: Steam Free Games Check

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  check-free-games:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests feedparser
        
    - name: Check free games and notify
      env:
        SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
      run: python check_steam_free.py
